# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choose_book_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('major_key', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=30)),
                ('book_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='choose_school_college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('major_key', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='seller_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('img_src1', models.CharField(max_length=300)),
                ('img_src2', models.CharField(max_length=300)),
                ('img_src3', models.CharField(max_length=300)),
                ('img_src4', models.CharField(max_length=300)),
                ('seller_description', models.CharField(max_length=160)),
                ('book_name', models.CharField(max_length=40)),
                ('book_author', models.CharField(max_length=30)),
                ('contactway', models.CharField(max_length=60)),
            ],
        ),
    ]
