# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer_front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='load_book_by_choose_major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('major_key', models.CharField(max_length=30)),
                ('book_img', models.CharField(max_length=500)),
                ('book_name', models.CharField(max_length=30)),
                ('book_key', models.CharField(max_length=20)),
            ],
        ),
    ]
