# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer_front', '0003_book_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_detail_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('major_key', models.CharField(max_length=30)),
                ('book_img', models.CharField(max_length=500)),
                ('book_name', models.CharField(max_length=30)),
                ('book_key', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('original_price', models.CharField(max_length=30)),
                ('publish_house', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20)),
                ('head_img', models.CharField(max_length=500)),
                ('wechat', models.CharField(max_length=30)),
                ('QQ', models.CharField(max_length=13)),
                ('school', models.CharField(max_length=20)),
                ('school_key', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('college_key', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('major_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('telphone', models.CharField(max_length=11)),
                ('book_key', models.CharField(max_length=20)),
            ],
        ),
    ]
