# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer_front', '0004_book_detail_new_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=256)),
                ('nickname', models.CharField(max_length=16)),
            ],
        ),
    ]
